name: Build resource pages

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'brownfield-land-collection/**'
      - 'brownfield-resources/**'
      - 'organisation-collection/**'
    branches:
      - master
  schedule:
    - cron: '0 6 * * *'

env:
  GITHUB_ACTOR_EMAIL: ${{ secrets.GITHUB_ACTOR_EMAIL }}
  GITHUB_ACTOR_TOKEN: ${{ secrets.GITHUB_ACTOR_TOKEN }}
  GITHUB_ACTOR_USERNAME: ${{ secrets.GITHUB_ACTOR_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Setup git
      run: |
        git config user.email "${GITHUB_ACTOR_EMAIL}"
        git config user.name "${GITHUB_ACTOR_USERNAME}"
        git remote set-url origin https://${GITHUB_ACTOR_USERNAME}:${GITHUB_ACTOR_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git checkout master
    - name: Install dependencies
      run: make init
    - name: Render files
      run: make render
    - name: Commit files
      run: |
        git add docs brownfield-land-collection organisation-collection brownfield-resources
        git diff --quiet && git diff --staged --quiet || (git commit -m "Build resource pages for $(date +%F)"; git push origin master)
